---
Name: productwishlistconfig
---
Member:
  extensions:
    - Dynamic\Wishlist\Extensions\WishListMemberDataExtension

ProductWishList:
  extensions:
    - Dynamic\ViewableDataObject\Extensions\ViewableDataObject
    - Dynamic\ManageableDataObject\Extensions\ManageableObjectDataExtension
  use_id: true
