---
Name: productwishlistconfig
---
SilverStripe\Security\Member:
  extensions:
    - Dynamic\Wishlist\Extensions\WishListMemberDataExtension

Dynamic\Wishlist\Model\ProductWishList:
  extensions:
    - Dynamic\ViewableDataObject\Extensions\ViewableDataObject
    - Dynamic\ManageableDataObject\Extensions\ManageableObjectDataExtension
  use_id: true
